### ISSUE TITLE
Can you make this compatible with tamed respawn

### ISSUE THREAD

**Issue by Mr-Syntax** [Lupicus/SaveYourPets#3]
What i expected to happen when i had both mods on is this
i give my horse extra lives and if it runs out i can use the pet bandage, but instead saveyourpets just overules 

can you make it wait till its depleted the extra lives from that mod before triggering? <3
https://www.curseforge.com/minecraft/mc-mods/tamedrespawn

**Comment by Lupicus** [comment]
That mod isn't open source, so I can't legally look at the code to see if I can make them compatible.
