### ISSUE TITLE
Foxhound from Quark mod

### ISSUE THREAD

**Issue by Edison12300** [Lupicus/SaveYourPets#4]
The foxhound from quark mod gets wounded whe it dies, but the bandage won't work on it.

**Comment by Lupicus** [comment]
What version of forge are you using?

**Comment by Edison12300** [comment]
Forge is 39.0.10

**Comment by Lupicus** [comment]
I loaded forge 39.0.10, Save Your Pets 1.0.0.6, Quark 3.0-334 and AutoRegLib 1.7-52
and created a new world. It seems to work for me. Maybe you have another mod that is interfering with this action. Does it work for a regular wolf?

**Comment by Edison12300** [comment]
Probably another mod then. It works fine on a regular wolf. Also, when I log back to my world, the foxhound is back to live. So maybe just another mod causing this to happen.

**Comment by Lupicus** [comment]
Hmm, strange the wolf works and not the foxhound, I'll take another look at it.
