### ISSUE TITLE
Mod conflict with Mahou Tsukai

### ISSUE THREAD

**Issue by InsipidSin** [Lupicus/SaveYourPets#5]
**Versions**
- Save Your Pets: 1.18 v1.0.0.7
- Mahou Tsukai: 1.18.1 v1.34.7
- Forge: 39.0.75
- Modpack: ATM7 v0.2.40
- Optifine Installed: No

**Expected Behavior**
Mahou Tsukai's Item (Sword) "Caliburn" converts to Item (Sword) "Morgan" after being used to kill a tamed wolf.

**Actual Behavior**
Upon being struck down, tamed wolf will be given your effect, ( Laying on floor and waiting to be revived) until duration is over. At that point in time, caliburn still does not receive the desired change to Morgan.

**Links/Images**
N/A

**Steps to Reproduce the Problem**
1. Obtain Caliburn.
2. Tame wolf
3. Kill wolf with Caliburn
4. Watch your dog die

**Comment by Lupicus** [comment]
Okay thanks, I'll take a look.

**Comment by Lupicus** [comment]
I didn't try this, but this is from ATM7 issue page:

Kill the tamed wolf with Caliburn
Have Caliburn in main hand and poisoned potato in offhand
Feed the wolf the poisoned potato killing it while Caliburn is actively in your hand

But the weapon was probably not active in your hand when the timer went off and pet dies.

**Comment by Lupicus** [comment]
Okay, I loaded the 2 mods. Both methods work. Just one is faster than the other. The important thing apparently with the conversion is the sword has to be active in your hand when the pet really dies.

**Comment by Lupicus** [comment]
Added poisonous potato option in late January (version 1.0.0.7) to help make things go faster and easier.
