### ISSUE TITLE
Unblock mod for third party launchers

### ISSUE THREAD

**Issue by ExistingExpert** [Lupicus/SaveYourPets#7]
May I ask why this mod was blocked for third-party launchers? I can only assume it was so that CF's download statistics are not messed up. Can this mod be unblocked? Many people don't, or straight up **can't** use Overwolf's launcher due to privacy concerns, and the fact that it is not available for linux (it only supports WOW). Due to this people have to manually download this mod everytime from the website (which, imo, is pretty meh) and forgo automatic updates for good.
![image](https://user-images.githubusercontent.com/71560815/174949323-1c02e045-c9db-4414-b862-2e114f010236.png)

**Comment by Lupicus** [comment]
My friend is evaluating the impact of making this change, but we currently only support the curse forge app.

**Comment by ExistingExpert** [comment]
Ah alright, thanks for taking it into consideration.
