### ISSUE TITLE
Mobs disappear when one-hit with weapons, no drops or death animation

### ISSUE THREAD

**Issue by vediis** [Lupicus/SaveYourPets#9]
Have had this issue while using a vanilla iron sword and hitting vanilla sheep, but also any fish in the sea. Animal makes hurt sound and disappears, showing heart particles and damage #, but no death sound, smoke particles, or mob drops. This only happens when the hit with the weapons would have been a one-hit. If hit with a lesser weapon, or with fists, this doesn't happen. The mob will take damage as usual and then have a usual death and usual drops. Also only applies to passive mobs - raccoons become hostile if I kill another (passive) racoon in front of them using this bug, and the newly-hostile raccoons are not affected by this.
https://gyazo.com/9bff3d95abc7c451eca9251e22fd06c8

Played with SaveYourPets added to the Chocolate modpack. https://www.modpackindex.com/modpack/65823/the-chocolate-edition-forge
Determined it was SaveYourPets causing this using a binary search method.

**Comment by Lupicus** [comment]
I loaded 1.19.2 forge with SYP mod and sheep can be one hit killed and loot drops and death animation happens. This mod has no change to untamable mobs like sheep. When I get around to it, I'll load the pack and check it out.

**Comment by Lupicus** [comment]
It appears you are correct, not sure how though. I'll look into it.

**Comment by Lupicus** [comment]
I've disabled almost all my code in the mod and it still happens. Something very strange.

**Comment by Lupicus** [comment]
Appears to be modid conflict. If I change my modid from syp to syp2 then it works.

**Comment by Lupicus** [comment]
dungeons_gear mod checks for syp mod loaded and performs some logic on death. That code is apparently wrong.
Removing it from the pack (and changing config/mobifier.json to remove references to that mod) makes it work correctly.
That mod needs to handle sheep and such correctly. It also might not drop loot from pets carrying items that are killed by single hit.
